= Order Service canvas
Chris Richardson <http://microservices.io>
Copyright (c) 2019 Chris Richardson Consulting Inc. All rights reserved


This canvas describes the `Order Service`, which is part of the https://github.com/microservices-patterns/ftgo-application/[FTGO application].

[cols="8*"]
|===
3+a| Name: 5+a| Serviço de Pedido

3+a| *Descrição:*
5+a|

O Serviço de Pedido fornece uma API para a criação, revisão e cancelamento de pedidos.

8+a| *Competências*
8+a|
Gerenciamento de Pedido
8+| *API do Serviço*
3+| Comandos 3+| Consultas 2+| Eventos Publicados
3+a| Síncronos:

* criarPedido()
* revisarPedido()
* cancelarPedido()

Assíncrono:

* N/A

 3+a| buscarPedido() 2+a| Canal de evento de Pedido:

* Pedido Criado
* Pedido Autorizado
* Pedido Revisado
* Pedido Cancelado
* ...

3+| Requisitos Não-Funcionais 5+a|

* 99.95% disponibilidade
* 1000 pedidos/segundo

8+| *Observalidade*
8+| Métricas-chave
8+a|

* pedido_feito
* pedido_aprovado
* pedido_rejeitado
* ...

4+| Health check endpoint
4+| /actuator/health



8+| *Implementation*
8+| Domain Model
8+a| * Order aggregate
8+| *Dependencies*
4+| Invokes 4+| Subscribes to
4+a|

Consumer Service:

* validateOrder()

Kitchen service:

* createTicket()
* confirmCreateTicket()
* cancelCreateTicket()

Accounting Service

* authorize()

 4+a| Restaurant Service

* Restaurant Created event
* Restaurant Menu Revised event

Saga reply channels:

* Create Order Saga
* Revise Order Saga
* Cancel Order Saga

|===
